"use client";

type Locale = "ar" | "en" | "ku" | "fr" | "hi" | "fa" | "tr" | "ru";

type ReportResult = {
  title?: string;
  lookup?: string;
  timePeriod?: string;
  period?: string;
  origin?: string;
  material?: string;
  style?: string;
  condition?: string;
  authenticity?: string;
  estimatedValue?: string;
  priceRange?: string;
  priceReasoning?: string;
  history?: string;
  description?: string;
  valueDrivers?: string[];
  valueReducers?: string[];
  neededPhotos?: string[];
  followUpQuestion?: string;
  confidence?: number;
  confidenceNote?: string;
  disclaimer?: string;
};

type AntiqueReportDocumentProps = {
  locale: Locale;
  result: ReportResult;
  imageUrl?: string;
  reportId?: string;
  generatedAt?: string;
  variant?: "preview" | "print";
};

const REPORT_LABELS: Record<
  Locale,
  {
    report: string;
    subtitle: string;
    preliminary: string;
    objectImage: string;
    identification: string;
    period: string;
    origin: string;
    material: string;
    style: string;
    value: string;
    condition: string;
    authenticity: string;
    priceReasoning: string;
    historicalContext: string;
    valueDrivers: string;
    valueReducers: string;
    neededPhotos: string;
    confidence: string;
    nextQuestion: string;
    disclaimerTitle: string;
    generatedBy: string;
    reportId: string;
    generatedAt: string;
    noImage: string;
    page: string;
  }
> = {
  ar: {
    report: "تقرير تقييم تحفة",
    subtitle: "تقييم بصري أولي للقطع التراثية والتحف والمجوهرات",
    preliminary: "تقييم أولي",
    objectImage: "صورة القطعة",
    identification: "التعريف",
    period: "العمر / الحقبة",
    origin: "المنشأ المحتمل",
    material: "المادة",
    style: "الأسلوب",
    value: "السعر التقديري",
    condition: "الحالة",
    authenticity: "الأصالة",
    priceReasoning: "سبب التقييم السعري",
    historicalContext: "الوصف والتحليل",
    valueDrivers: "عوامل ترفع القيمة",
    valueReducers: "عوامل تقلل القيمة",
    neededPhotos: "صور مطلوبة للتأكيد",
    confidence: "درجة الثقة",
    nextQuestion: "السؤال التالي",
    disclaimerTitle: "تنبيه مهم",
    generatedBy: "Generated by KISHIB",
    reportId: "رقم التقرير",
    generatedAt: "تاريخ الإنشاء",
    noImage: "لا توجد صورة",
    page: "صفحة",
  },
  en: {
    report: "Antique Evaluation Report",
    subtitle: "Preliminary visual assessment for antiques, heritage objects, and jewelry",
    preliminary: "Preliminary evaluation",
    objectImage: "Object image",
    identification: "Identification",
    period: "Period / age",
    origin: "Possible origin",
    material: "Material",
    style: "Style",
    value: "Estimated value",
    condition: "Condition",
    authenticity: "Authenticity",
    priceReasoning: "Price reasoning",
    historicalContext: "Description and analysis",
    valueDrivers: "Value drivers",
    valueReducers: "Value reducers",
    neededPhotos: "Photos needed for verification",
    confidence: "Confidence score",
    nextQuestion: "Next question",
    disclaimerTitle: "Important notice",
    generatedBy: "Generated by KISHIB",
    reportId: "Report ID",
    generatedAt: "Generated at",
    noImage: "No image available",
    page: "Page",
  },
  ku: {
    report: "ڕاپۆرتی هەڵسەنگاندنی ئانتیک",
    subtitle: "هەڵسەنگاندنی سەرەتایی بۆ شتومەکی کۆن و کولتووری",
    preliminary: "هەڵسەنگاندنی سەرەتایی",
    objectImage: "وێنەی شتەکە",
    identification: "ناساندن",
    period: "سەردەم / تەمەن",
    origin: "سەرچاوەی ئەگەری",
    material: "ماددە",
    style: "شێواز",
    value: "نرخی مەزەندەکراو",
    condition: "دۆخ",
    authenticity: "ڕەسەنایەتی",
    priceReasoning: "هۆکاری نرخدانان",
    historicalContext: "وەسف و شیکردنەوە",
    valueDrivers: "هۆکارەکانی زیادبوونی بەها",
    valueReducers: "هۆکارەکانی کەمبوونی بەها",
    neededPhotos: "وێنەی پێویست بۆ پشتڕاستکردنەوە",
    confidence: "پلەی دڵنیایی",
    nextQuestion: "پرسیاری دواتر",
    disclaimerTitle: "ئاگاداری گرنگ",
    generatedBy: "Generated by KISHIB",
    reportId: "ژمارەی ڕاپۆرت",
    generatedAt: "دروستکراوە لە",
    noImage: "هیچ وێنەیەک نییە",
    page: "لاپەڕە",
  },
  fr: {
    report: "Rapport d’évaluation d’antiquité",
    subtitle: "Évaluation visuelle préliminaire des antiquités et bijoux",
    preliminary: "Évaluation préliminaire",
    objectImage: "Image de l’objet",
    identification: "Identification",
    period: "Période / âge",
    origin: "Origine possible",
    material: "Matériau",
    style: "Style",
    value: "Valeur estimée",
    condition: "État",
    authenticity: "Authenticité",
    priceReasoning: "Justification du prix",
    historicalContext: "Description et analyse",
    valueDrivers: "Facteurs de valeur",
    valueReducers: "Facteurs réduisant la valeur",
    neededPhotos: "Photos nécessaires",
    confidence: "Niveau de confiance",
    nextQuestion: "Question suivante",
    disclaimerTitle: "Avis important",
    generatedBy: "Generated by KISHIB",
    reportId: "ID du rapport",
    generatedAt: "Généré le",
    noImage: "Aucune image disponible",
    page: "Page",
  },
  hi: {} as any,
  fa: {} as any,
  tr: {} as any,
  ru: {} as any,
};

REPORT_LABELS.hi = REPORT_LABELS.en;
REPORT_LABELS.fa = REPORT_LABELS.ar;
REPORT_LABELS.tr = REPORT_LABELS.en;
REPORT_LABELS.ru = REPORT_LABELS.en;

function getDirection(locale: Locale) {
  return locale === "ar" || locale === "ku" || locale === "fa" ? "rtl" : "ltr";
}

function cleanText(value?: string) {
  if (!value || !value.trim()) return "—";
  return value.trim();
}

function getDefaultDisclaimer(locale: Locale) {
  if (locale === "en" || locale === "hi" || locale === "tr" || locale === "ru") {
    return "This report is a preliminary visual evaluation based on the provided image and information. It is not an authenticity certificate, legal valuation, insurance appraisal, or auction guarantee.";
  }

  if (locale === "fr") {
    return "Ce rapport est une évaluation visuelle préliminaire basée sur l’image et les informations fournies. Il ne constitue pas un certificat d’authenticité, une expertise légale, une estimation d’assurance ou une garantie de vente aux enchères.";
  }

  if (locale === "ku") {
    return "ئەم ڕاپۆرتە هەڵسەنگاندنێکی سەرەتاییە بە پشتبەستن بە وێنە و زانیاریی پێشکەشکراو. ئەمە بڕوانامەی ڕەسەنایەتی، نرخدانانی یاسایی، هەڵسەنگاندنی بیمە، یان گەرەنتی مزایدە نییە.";
  }

  return "هذا التقرير هو تقييم بصري أولي بالاعتماد على الصورة والمعلومات المقدمة. لا يُعد شهادة أصالة، أو تخميناً قانونياً، أو تقييماً تأمينياً، أو ضماناً للبيع في المزاد.";
}

function formatDate(locale: Locale, generatedAt?: string) {
  if (generatedAt) return generatedAt;

  const dateLocale =
    locale === "ar" ? "ar-IQ" : locale === "fr" ? "fr-FR" : "en-US";

  return new Intl.DateTimeFormat(dateLocale, {
    year: "numeric",
    month: "short",
    day: "2-digit",
  }).format(new Date());
}

function InfoBlock({
  label,
  value,
  strong = false,
}: {
  label: string;
  value?: string;
  strong?: boolean;
}) {
  return (
    <div className="rounded-[14px] border border-[#e5d4ba] bg-white/64 p-3">
      <p className="mb-1 text-[8.5px] font-black uppercase tracking-[0.14em] text-[#9a7441]">
        {label}
      </p>
      <p
        className={[
          "whitespace-pre-line break-words leading-[1.65] text-[#241b14]",
          strong
            ? "text-[13.5px] font-black text-[#9a5f18]"
            : "text-[11.2px] font-semibold",
        ].join(" ")}
      >
        {cleanText(value)}
      </p>
    </div>
  );
}

function TextBox({
  title,
  body,
  compact = false,
}: {
  title: string;
  body?: string;
  compact?: boolean;
}) {
  return (
    <section className="rounded-[16px] border border-[#e5d4ba] bg-white/64 p-4">
      <h3 className="mb-2 text-[9px] font-black uppercase tracking-[0.16em] text-[#9a7441]">
        {title}
      </h3>
      <p
        className={[
          "whitespace-pre-line break-words font-semibold text-[#2a2119]",
          compact ? "text-[10.2px] leading-[1.72]" : "text-[11px] leading-[1.82]",
        ].join(" ")}
      >
        {cleanText(body)}
      </p>
    </section>
  );
}

function ListSection({
  title,
  items,
}: {
  title: string;
  items?: string[];
}) {
  const safeItems = Array.isArray(items) ? items.filter(Boolean) : [];

  if (safeItems.length === 0) {
    return <TextBox title={title} body="—" compact />;
  }

  return (
    <section className="rounded-[16px] border border-[#e5d4ba] bg-white/64 p-4">
      <h3 className="mb-2 text-[9px] font-black uppercase tracking-[0.16em] text-[#9a7441]">
        {title}
      </h3>

      <div className="grid gap-1.5">
        {safeItems.map((item, index) => (
          <div
            key={`${title}-${index}`}
            className="flex gap-2 rounded-[10px] bg-[#f8f1e8] px-2.5 py-1.5 text-[10.2px] font-semibold leading-[1.62] text-[#33251b]"
          >
            <span className="mt-[2px] flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-[#2a2119] text-[8px] text-[#f5d8a7]">
              {index + 1}
            </span>
            <span className="break-words">{item}</span>
          </div>
        ))}
      </div>
    </section>
  );
}

function ReportPage({
  children,
  pageNumber,
  labels,
}: {
  children: React.ReactNode;
  pageNumber: string;
  labels: { generatedBy: string; page: string };
}) {
  return (
    <div className="report-page relative h-[1123px] w-[794px] shrink-0 overflow-hidden bg-[#f7f0e6] p-[30px] print:h-[297mm] print:w-[210mm]">
      <div className="pointer-events-none absolute inset-[18px] rounded-[24px] border border-[#d8c5a8]" />
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top,#fffaf2_0%,rgba(255,255,255,0)_36%),linear-gradient(135deg,rgba(154,116,65,0.12),rgba(255,255,255,0)_35%)]" />

      <div className="relative z-10 h-full">
        {children}

        <div className="absolute bottom-0 left-0 right-0 flex items-center justify-between border-t border-[#dfcfb7] pt-2 text-[9px] font-bold text-[#9a7441]/70">
          <span>{labels.generatedBy}</span>
          <span>
            {labels.page} {pageNumber}
          </span>
        </div>
      </div>
    </div>
  );
}

export default function AntiqueReportDocument({
  locale,
  result,
  imageUrl,
  reportId,
  generatedAt,
  variant = "preview",
}: AntiqueReportDocumentProps) {
  const labels = REPORT_LABELS[locale] || REPORT_LABELS.ar;
  const dir = getDirection(locale);
  const dateText = formatDate(locale, generatedAt);

  const period = result.timePeriod || result.period;
  const value = result.estimatedValue || result.priceRange;
  const history = result.history || result.description;

  return (
    <article
      dir={dir}
      className={[
        "antique-report-document mx-auto text-[#211a15]",
        variant === "print"
          ? "w-[794px]"
          : "w-full max-w-[794px] overflow-visible rounded-[2rem] shadow-2xl shadow-black/20",
      ].join(" ")}
    >
      <div className={variant === "print" ? "" : "space-y-6"}>
        <ReportPage pageNumber="1 / 2" labels={labels}>
          <header className="mb-5 flex items-start justify-between gap-5 border-b border-[#dfcfb7] pb-4">
            <div className="flex items-center gap-3">
              <div className="flex h-12 w-12 items-center justify-center rounded-[18px] bg-[#1f1711] text-[16px] font-black text-[#f5d8a7]">
                K
              </div>

              <div>
                <p className="text-[9px] font-black uppercase tracking-[0.22em] text-[#9a7441]">
                  {labels.preliminary}
                </p>
                <h1 className="mt-1 text-[24px] font-black leading-tight tracking-tight text-[#1c1713]">
                  {labels.report}
                </h1>
                <p className="mt-1 text-[10.5px] font-semibold text-[#745f4b]">
                  {labels.subtitle}
                </p>
              </div>
            </div>

            <div className="max-w-[220px] text-end text-[9.5px] font-bold leading-5 text-[#7b6653]">
              {reportId ? (
                <p>
                  <span className="text-[#9a7441]">{labels.reportId}: </span>
                  {reportId}
                </p>
              ) : null}
              <p>
                <span className="text-[#9a7441]">{labels.generatedAt}: </span>
                {dateText}
              </p>
            </div>
          </header>

          <section className="mb-5 text-center">
            <h2 className="mx-auto max-w-[670px] break-words text-[23px] font-black leading-[1.28] text-[#1e1712]">
              {cleanText(result.title)}
            </h2>
          </section>

          <section className="mb-5 grid grid-cols-[245px_1fr] gap-4">
            <div className="rounded-[18px] border border-[#dfcfb7] bg-[#efe3d2] p-3">
              <p className="mb-2 text-[8.5px] font-black uppercase tracking-[0.18em] text-[#9a7441]">
                {labels.objectImage}
              </p>

              {imageUrl ? (
                <div className="flex h-[250px] items-center justify-center rounded-[14px] bg-[#1f1711] p-2">
                  <img
                    src={imageUrl}
                    alt={result.title || labels.objectImage}
                    className="max-h-full max-w-full rounded-[10px] object-contain"
                  />
                </div>
              ) : (
                <div className="flex h-[250px] items-center justify-center rounded-[14px] bg-[#d8c5a8] text-[11px] font-bold text-[#735b42]">
                  {labels.noImage}
                </div>
              )}
            </div>

            <div className="grid gap-2.5">
              <InfoBlock label={labels.identification} value={result.lookup} />
              <div className="grid grid-cols-2 gap-2.5">
                <InfoBlock label={labels.period} value={period} />
                <InfoBlock label={labels.origin} value={result.origin} />
              </div>
              <div className="grid grid-cols-2 gap-2.5">
                <InfoBlock label={labels.material} value={result.material} />
                <InfoBlock label={labels.style} value={result.style} />
              </div>
              <InfoBlock label={labels.value} value={value} strong />
            </div>
          </section>

          <section className="mb-5 grid grid-cols-2 gap-3">
            <TextBox title={labels.condition} body={result.condition} compact />
            <TextBox title={labels.authenticity} body={result.authenticity} compact />
          </section>

          <TextBox title={labels.priceReasoning} body={result.priceReasoning} />
        </ReportPage>

        <ReportPage pageNumber="2 / 2" labels={labels}>
          <header className="mb-5 flex items-center justify-between border-b border-[#dfcfb7] pb-4">
            <div className="min-w-0">
              <p className="text-[9px] font-black uppercase tracking-[0.22em] text-[#9a7441]">
                {labels.report}
              </p>
              <h2 className="mt-1 max-w-[640px] break-words text-[21px] font-black leading-[1.25] text-[#1c1713]">
                {cleanText(result.title)}
              </h2>
            </div>

            <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-[16px] bg-[#1f1711] text-[14px] font-black text-[#f5d8a7]">
              K
            </div>
          </header>

          <section className="mb-4">
            <TextBox title={labels.historicalContext} body={history} />
          </section>

          <section className="mb-4 grid grid-cols-2 gap-3">
            <ListSection title={labels.valueDrivers} items={result.valueDrivers} />
            <ListSection title={labels.valueReducers} items={result.valueReducers} />
          </section>

          <section className="mb-4 grid grid-cols-2 gap-3">
            <ListSection title={labels.neededPhotos} items={result.neededPhotos} />

            <section className="rounded-[16px] border border-[#e5d4ba] bg-white/64 p-4">
              <h3 className="mb-2 text-[9px] font-black uppercase tracking-[0.16em] text-[#9a7441]">
                {labels.confidence}
              </h3>

              <div className="mb-2 flex items-end gap-2">
                <span className="text-[30px] font-black leading-none text-[#9a5f18]">
                  {typeof result.confidence === "number" ? result.confidence : "—"}
                </span>
                <span className="pb-1 text-[11px] font-bold text-[#745f4b]">/ 10</span>
              </div>

              <p className="whitespace-pre-line break-words text-[10.3px] font-semibold leading-[1.65] text-[#33251b]">
                {cleanText(result.confidenceNote)}
              </p>

              {result.followUpQuestion ? (
                <div className="mt-3 rounded-[12px] bg-[#f8f1e8] p-3">
                  <p className="mb-1 text-[8.5px] font-black uppercase tracking-[0.16em] text-[#9a7441]">
                    {labels.nextQuestion}
                  </p>
                  <p className="whitespace-pre-line break-words text-[10.2px] font-semibold leading-[1.65] text-[#2a2119]">
                    {result.followUpQuestion}
                  </p>
                </div>
              ) : null}
            </section>
          </section>

          <footer className="absolute bottom-[34px] left-0 right-0 overflow-hidden rounded-[18px] bg-[#1f1711] p-4 text-center text-[#f8ead5]">
            <p className="mb-1 text-[9px] font-black uppercase tracking-[0.22em] text-[#d6a45d]">
              {labels.disclaimerTitle}
            </p>
            <p className="mx-auto max-w-[650px] whitespace-pre-line break-words text-[10px] font-semibold leading-[1.65] text-[#f8ead5]/86">
              {result.disclaimer || getDefaultDisclaimer(locale)}
            </p>
          </footer>
        </ReportPage>
      </div>

      <style jsx global>{`
        .antique-report-document,
        .antique-report-document * {
          box-sizing: border-box;
        }

        .report-page {
          page-break-after: always;
          break-after: page;
        }

        .report-page:last-child {
          page-break-after: auto;
          break-after: auto;
        }

        @media print {
          html,
          body {
            margin: 0 !important;
            padding: 0 !important;
            background: white !important;
          }

          body * {
            visibility: hidden !important;
          }

          .report-print-area,
          .report-print-area * {
            visibility: visible !important;
          }

          .report-print-area {
            position: absolute !important;
            inset: 0 auto auto 0 !important;
            width: 210mm !important;
            margin: 0 !important;
            padding: 0 !important;
            border: none !important;
            background: white !important;
            overflow: visible !important;
            opacity: 1 !important;
            pointer-events: auto !important;
          }

          .report-print-area .antique-report-document {
            width: 210mm !important;
            max-width: none !important;
            margin: 0 !important;
            border-radius: 0 !important;
            box-shadow: none !important;
            overflow: visible !important;
          }

          .report-print-area .report-page {
            width: 210mm !important;
            height: 297mm !important;
            margin: 0 !important;
            padding: 8mm !important;
            overflow: hidden !important;
          }

          @page {
            size: A4;
            margin: 0;
          }
        }
      `}</style>
    </article>
  );
}