import type { AnalysisResult } from "./types";

export const HISTORY_KEY = "antiques-lens:history-v2";

export const content = {
  ar: {
    dir: "rtl",
    new: "تقييم جديد",
    archive: "أرشيف القطع",
    emptyArchive: "لا توجد تقييمات بعد.",
    clearArchive: "مسح",
    openArchive: "الأرشيف",
    badge: "Antiques Lens",
    sub: "AI antique evaluator",
    title: "صوّر أي قطعة أنتيكة",
    hint: "ارفع صورة واضحة أو التقط صورة للقطعة، وسنحاول تحديد العمر، المادة، الحالة، السعر، والقطع المشابهة.",
    placeholder: "اكتب أي معلومة تعرفها...",
    upload: "رفع صورة",
    camera: "الكاميرا",
    send: "تحليل",
    analyzing: "جاري التحليل...",
    emptyError: "أضف وصفاً أو ارفع صورة للقطعة أولاً.",
    imageReady: "الصورة مرفقة",
    footer: "لنتيجة أدق: صورة كاملة + صورة للختم أو التوقيع إن وجد.",
    result: "نتيجة أولية",
    age: "العمر / الحقبة",
    value: "السعر التقريبي",
    material: "المادة",
    origin: "المنشأ",
    lookup: "التعريف",
    description: "الوصف والتحليل",
    condition: "الحالة الظاهرة",
    authenticity: "مؤشرات الأصالة",
    priceReason: "سبب السعر",
    valueDrivers: "ما الذي يرفع القيمة؟",
    valueReducers: "ما الذي يخفض القيمة؟",
    similar: "قطع مشابهة",
    similarHint: "بعد ربط eBay ستظهر هنا صور وأسعار وروابط حقيقية.",
    soon: "قريباً eBay",
    neededPhotos: "صور مطلوبة لتقييم أدق",
    followUp: "السؤال التالي",
    confidence: "درجة الثقة",
    share: "مشاركة",
    addInfo: "أضف معلومات",
    notice: "التقييم استرشادي ولا يعتبر شهادة أصالة أو تسعيراً نهائياً.",
  },

  en: {
    dir: "ltr",
    new: "New evaluation",
    archive: "Pieces archive",
    emptyArchive: "No evaluations yet.",
    clearArchive: "Clear",
    openArchive: "Archive",
    badge: "Antiques Lens",
    sub: "AI antique evaluator",
    title: "Scan any antique object",
    hint: "Upload or capture a clear image, and we will estimate age, material, condition, value, and similar references.",
    placeholder: "Add anything you know...",
    upload: "Upload image",
    camera: "Camera",
    send: "Analyze",
    analyzing: "Analyzing...",
    emptyError: "Add a description or upload an image first.",
    imageReady: "Image attached",
    footer: "For better accuracy: full image + mark or signature if available.",
    result: "Initial result",
    age: "Age / Period",
    value: "Estimated value",
    material: "Material",
    origin: "Origin",
    lookup: "Look up",
    description: "Description",
    condition: "Visible condition",
    authenticity: "Authenticity indicators",
    priceReason: "Price reasoning",
    valueDrivers: "What increases value?",
    valueReducers: "What reduces value?",
    similar: "Similar pieces",
    similarHint: "After connecting eBay, real images, prices, and links will appear here.",
    soon: "eBay soon",
    neededPhotos: "Photos needed",
    followUp: "Next question",
    confidence: "Confidence",
    share: "Share",
    addInfo: "Add info",
    notice: "This is an indicative evaluation, not an authenticity certificate or final appraisal.",
  },

  ku: {
    dir: "rtl",
    new: "هەڵسەنگاندنی نوێ",
    archive: "ئەرشیفی پارچەکان",
    emptyArchive: "هێشتا هیچ هەڵسەنگاندنێک نییە.",
    clearArchive: "سڕینەوە",
    openArchive: "ئەرشیف",
    badge: "Antiques Lens",
    sub: "AI antique evaluator",
    title: "هەر پارچەیەکی کۆن وێنە بگرە",
    hint: "وێنەیەکی ڕوون باربکە و هەوڵ دەدەین تەمەن، مادە، دۆخ، نرخ و هاوشێوەکانی دیاری بکەین.",
    placeholder: "هەر زانیارییەک دەزانیت بنووسە...",
    upload: "بارکردنی وێنە",
    camera: "کامێرا",
    send: "شیکردنەوە",
    analyzing: "شیکردنەوە...",
    emptyError: "سەرەتا وەسفێک زیاد بکە یان وێنەیەک باربکە.",
    imageReady: "وێنە هاوپێچ کرا",
    footer: "بۆ ئەنجامی وردتر: وێنەی تەواو + وێنەی مۆر یان واژۆ ئەگەر هەبوو.",
    result: "ئەنجامی سەرەتایی",
    age: "تەمەن / سەردەم",
    value: "نرخی نزیک",
    material: "مادە",
    origin: "سەرچاوە",
    lookup: "ناسینەوە",
    description: "وەسف و شیکردنەوە",
    condition: "دۆخی دیار",
    authenticity: "نیشانەکانی ڕەسەنایەتی",
    priceReason: "هۆکاری نرخ",
    valueDrivers: "چی نرخ زیاد دەکات؟",
    valueReducers: "چی نرخ کەم دەکات؟",
    similar: "پارچەی هاوشێوە",
    similarHint: "دوای بەستنەوەی eBay، وێنە و نرخ و لینک ڕاستەقینە دەردەکەون.",
    soon: "eBay بە زوویی",
    neededPhotos: "وێنەی پێویست",
    followUp: "پرسیاری دواتر",
    confidence: "ئاستی دڵنیایی",
    share: "هاوبەشکردن",
    addInfo: "زانیاری زیاد بکە",
    notice: "ئەمە هەڵسەنگاندنێکی ڕێنماییە، نە بڕوانامەی ڕەسەنایەتی یان نرخاندنی کۆتایی.",
  },

  fr: {
    dir: "ltr",
    new: "Nouvelle évaluation",
    archive: "Archive des pièces",
    emptyArchive: "Aucune évaluation pour le moment.",
    clearArchive: "Effacer",
    openArchive: "Archive",
    badge: "Antiques Lens",
    sub: "AI antique evaluator",
    title: "Scannez n’importe quelle antiquité",
    hint: "Ajoutez ou prenez une image claire, et nous estimerons l’âge, la matière, l’état, la valeur et les références similaires.",
    placeholder: "Ajoutez ce que vous savez...",
    upload: "Ajouter une image",
    camera: "Caméra",
    send: "Analyser",
    analyzing: "Analyse en cours...",
    emptyError: "Ajoutez une description ou une image d’abord.",
    imageReady: "Image jointe",
    footer: "Pour plus de précision : image complète + marque ou signature si disponible.",
    result: "Résultat initial",
    age: "Âge / Période",
    value: "Valeur estimée",
    material: "Matière",
    origin: "Origine",
    lookup: "Identification",
    description: "Description",
    condition: "État visible",
    authenticity: "Indices d’authenticité",
    priceReason: "Justification du prix",
    valueDrivers: "Ce qui augmente la valeur",
    valueReducers: "Ce qui réduit la valeur",
    similar: "Pièces similaires",
    similarHint: "Après la connexion à eBay, les images, prix et liens réels apparaîtront ici.",
    soon: "eBay bientôt",
    neededPhotos: "Photos nécessaires",
    followUp: "Question suivante",
    confidence: "Confiance",
    share: "Partager",
    addInfo: "Ajouter info",
    notice: "Cette évaluation est indicative et ne constitue pas un certificat d’authenticité ni une estimation finale.",
  },
} as const;

export type ContentItem = (typeof content)[keyof typeof content];

export function normalizeResult(data: Partial<AnalysisResult>): AnalysisResult {
  return {
    title: data.title || data.itemType || "Antique item",
    lookup: data.lookup || data.description || "",
    timePeriod: data.timePeriod || data.period || "غير واضح",
    origin: data.origin || "غير واضح",
    material: data.material || "غير واضح",
    style: data.style || "غير واضح",
    condition: data.condition || "غير واضح",
    authenticity: data.authenticity || "لا يمكن الجزم من الصورة فقط.",
    estimatedValue: data.estimatedValue || data.priceRange || "غير واضح",
    priceReasoning: data.priceReasoning || "",
    history: data.history || data.description || "",
    valueDrivers: Array.isArray(data.valueDrivers) ? data.valueDrivers : [],
    valueReducers: Array.isArray(data.valueReducers) ? data.valueReducers : [],
    visualSearchKeywords: Array.isArray(data.visualSearchKeywords)
      ? data.visualSearchKeywords
      : Array.isArray(data.keywords)
        ? data.keywords
        : [],
    neededPhotos: Array.isArray(data.neededPhotos) ? data.neededPhotos : [],
    followUpQuestion: data.followUpQuestion || "",
    confidence:
      typeof data.confidence === "number"
        ? Math.min(10, Math.max(1, data.confidence))
        : 3,
    confidenceNote: data.confidenceNote || "",
    disclaimer: data.disclaimer || "",
    itemType: data.itemType,
    description: data.description,
    priceRange: data.priceRange,
    period: data.period,
    keywords: data.keywords,
  };
}