"use client";

type Locale = "ar" | "en" | "ku" | "fr";

type ReportResult = {
  title?: string;
  lookup?: string;
  timePeriod?: string;
  origin?: string;
  material?: string;
  style?: string;
  condition?: string;
  authenticity?: string;
  estimatedValue?: string;
  priceReasoning?: string;
  history?: string;
  valueDrivers?: string[];
  valueReducers?: string[];
  neededPhotos?: string[];
  followUpQuestion?: string;
  confidence?: number;
  confidenceNote?: string;
  disclaimer?: string;
};

type AntiqueReportDocumentProps = {
  locale: Locale;
  result: ReportResult;
  imageUrl?: string;
  reportId?: string;
  generatedAt?: string;
  variant?: "preview" | "print";
};

const REPORT_LABELS: Record<
  Locale,
  {
    report: string;
    subtitle: string;
    preliminary: string;
    objectImage: string;
    identification: string;
    period: string;
    origin: string;
    material: string;
    style: string;
    value: string;
    condition: string;
    authenticity: string;
    priceReasoning: string;
    historicalContext: string;
    valueDrivers: string;
    valueReducers: string;
    neededPhotos: string;
    confidence: string;
    nextQuestion: string;
    disclaimerTitle: string;
    generatedBy: string;
    reportId: string;
    generatedAt: string;
    noImage: string;
  }
> = {
  ar: {
    report: "تقرير تقييم تحفة",
    subtitle: "تقييم بصري أولي للقطع التراثية والتحف",
    preliminary: "تقييم أولي",
    objectImage: "صورة القطعة",
    identification: "التعريف",
    period: "العمر / الحقبة",
    origin: "المنشأ المحتمل",
    material: "المادة",
    style: "الأسلوب",
    value: "السعر التقديري",
    condition: "الحالة",
    authenticity: "الأصالة",
    priceReasoning: "سبب التقييم السعري",
    historicalContext: "الوصف والتحليل",
    valueDrivers: "عوامل ترفع القيمة",
    valueReducers: "عوامل تقلل القيمة",
    neededPhotos: "صور مطلوبة للتأكيد",
    confidence: "درجة الثقة",
    nextQuestion: "السؤال التالي",
    disclaimerTitle: "تنبيه مهم",
    generatedBy: "Generated by Antique Lens",
    reportId: "رقم التقرير",
    generatedAt: "تاريخ الإنشاء",
    noImage: "لا توجد صورة",
  },
  en: {
    report: "Antique Evaluation Report",
    subtitle: "Preliminary visual assessment for antiques and heritage objects",
    preliminary: "Preliminary evaluation",
    objectImage: "Object image",
    identification: "Identification",
    period: "Period / age",
    origin: "Possible origin",
    material: "Material",
    style: "Style",
    value: "Estimated value",
    condition: "Condition",
    authenticity: "Authenticity",
    priceReasoning: "Price reasoning",
    historicalContext: "Description and analysis",
    valueDrivers: "Value drivers",
    valueReducers: "Value reducers",
    neededPhotos: "Photos needed for verification",
    confidence: "Confidence score",
    nextQuestion: "Next question",
    disclaimerTitle: "Important notice",
    generatedBy: "Generated by Antique Lens",
    reportId: "Report ID",
    generatedAt: "Generated at",
    noImage: "No image available",
  },
  ku: {
    report: "ڕاپۆرتی هەڵسەنگاندنی ئانتیک",
    subtitle: "هەڵسەنگاندنی سەرەتایی بە بینین بۆ شتومەکی کۆن و کولتووری",
    preliminary: "هەڵسەنگاندنی سەرەتایی",
    objectImage: "وێنەی شتەکە",
    identification: "ناساندن",
    period: "سەردەم / تەمەن",
    origin: "سەرچاوەی ئەگەری",
    material: "ماددە",
    style: "شێواز",
    value: "نرخی مەزەندەکراو",
    condition: "دۆخ",
    authenticity: "ڕەسەنایەتی",
    priceReasoning: "هۆکاری نرخدانان",
    historicalContext: "وەسف و شیکردنەوە",
    valueDrivers: "هۆکارەکانی زیادبوونی بەها",
    valueReducers: "هۆکارەکانی کەمبوونی بەها",
    neededPhotos: "وێنەی پێویست بۆ پشتڕاستکردنەوە",
    confidence: "پلەی دڵنیایی",
    nextQuestion: "پرسیاری دواتر",
    disclaimerTitle: "ئاگاداری گرنگ",
    generatedBy: "Generated by Antique Lens",
    reportId: "ژمارەی ڕاپۆرت",
    generatedAt: "دروستکراوە لە",
    noImage: "هیچ وێنەیەک نییە",
  },
  fr: {
    report: "Rapport d’évaluation d’antiquité",
    subtitle: "Évaluation visuelle préliminaire des antiquités et objets patrimoniaux",
    preliminary: "Évaluation préliminaire",
    objectImage: "Image de l’objet",
    identification: "Identification",
    period: "Période / âge",
    origin: "Origine possible",
    material: "Matériau",
    style: "Style",
    value: "Valeur estimée",
    condition: "État",
    authenticity: "Authenticité",
    priceReasoning: "Justification du prix",
    historicalContext: "Description et analyse",
    valueDrivers: "Facteurs de valeur",
    valueReducers: "Facteurs réduisant la valeur",
    neededPhotos: "Photos nécessaires pour vérification",
    confidence: "Niveau de confiance",
    nextQuestion: "Question suivante",
    disclaimerTitle: "Avis important",
    generatedBy: "Generated by Antique Lens",
    reportId: "ID du rapport",
    generatedAt: "Généré le",
    noImage: "Aucune image disponible",
  },
};

function getDirection(locale: Locale) {
  return locale === "ar" || locale === "ku" ? "rtl" : "ltr";
}

function cleanText(value?: string) {
  if (!value) return "—";
  return value.trim();
}

function getDefaultDisclaimer(locale: Locale) {
  if (locale === "en") {
    return "This report is a preliminary visual evaluation based on the provided image and information. It is not an authenticity certificate, legal valuation, insurance appraisal, or auction guarantee.";
  }

  if (locale === "fr") {
    return "Ce rapport est une évaluation visuelle préliminaire basée sur l’image et les informations fournies. Il ne constitue pas un certificat d’authenticité, une expertise légale, une estimation d’assurance ou une garantie de vente aux enchères.";
  }

  if (locale === "ku") {
    return "ئەم ڕاپۆرتە هەڵسەنگاندنێکی سەرەتاییە بە پشتبەستن بە وێنە و زانیاریی پێشکەشکراو. ئەمە بڕوانامەی ڕەسەنایەتی، نرخدانانی یاسایی، هەڵسەنگاندنی بیمە، یان گەرەنتی مزایدە نییە.";
  }

  return "هذا التقرير هو تقييم بصري أولي بالاعتماد على الصورة والمعلومات المقدمة. لا يُعد شهادة أصالة، أو تخميناً قانونياً، أو تقييماً تأمينياً، أو ضماناً للبيع في المزاد.";
}

function InfoBlock({
  label,
  value,
  strong = false,
}: {
  label: string;
  value?: string;
  strong?: boolean;
}) {
  return (
    <div className="rounded-2xl border border-[#e7dccb] bg-white/70 p-4">
      <p className="mb-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-[#9a7441]">
        {label}
      </p>
      <p
        className={[
          "leading-7 text-[#211a15]",
          strong ? "text-[18px] font-black text-[#9a5f18]" : "text-[13px] font-medium",
        ].join(" ")}
      >
        {cleanText(value)}
      </p>
    </div>
  );
}

function ListSection({
  title,
  items,
}: {
  title: string;
  items?: string[];
}) {
  const safeItems = Array.isArray(items) ? items.filter(Boolean) : [];

  if (safeItems.length === 0) return null;

  return (
    <section className="rounded-2xl border border-[#e7dccb] bg-white/65 p-5">
      <h3 className="mb-3 text-[12px] font-black uppercase tracking-[0.18em] text-[#9a7441]">
        {title}
      </h3>

      <div className="grid gap-2">
        {safeItems.slice(0, 5).map((item, index) => (
          <div
            key={`${title}-${index}`}
            className="flex gap-2 rounded-xl bg-[#f8f1e8] px-3 py-2 text-[12px] font-semibold leading-6 text-[#33251b]"
          >
            <span className="mt-[2px] flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#2a2119] text-[10px] text-[#f5d8a7]">
              {index + 1}
            </span>
            <span>{item}</span>
          </div>
        ))}
      </div>
    </section>
  );
}
function ReportPage({ children }: { children: React.ReactNode }) {
  return (
    <div className="report-page relative h-[1123px] w-[794px] overflow-hidden bg-[#f7f0e6] p-7 print:h-[297mm] print:w-[210mm] print:p-6">
      <div className="pointer-events-none absolute inset-4 rounded-[1.6rem] border border-[#d8c5a8]" />
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top,#fffaf2_0%,rgba(255,255,255,0)_38%),linear-gradient(135deg,rgba(154,116,65,0.12),rgba(255,255,255,0)_35%)]" />
      <div className="relative z-10">{children}</div>
    </div>
  );
}
export default function AntiqueReportDocument({
  locale,
  result,
  imageUrl,
  reportId,
  generatedAt,
  variant = "preview",
}: AntiqueReportDocumentProps) {
  const labels = REPORT_LABELS[locale] || REPORT_LABELS.ar;
  const dir = getDirection(locale);

  const dateText =
    generatedAt ||
    new Intl.DateTimeFormat(locale === "ar" ? "ar-IQ" : "en-US", {
      year: "numeric",
      month: "short",
      day: "2-digit",
    }).format(new Date());

  return (
 <article
  dir={dir}
  className={[
    "antique-report-document mx-auto bg-[#f7f0e6] text-[#211a15]",
    variant === "print"
      ? "w-[794px]"
      : "w-full max-w-[794px] rounded-[2rem] shadow-2xl shadow-black/20",
  ].join(" ")}
>
      <div className="relative h-[1123px] overflow-hidden p-7 print:p-6">
        <div className="pointer-events-none absolute inset-4 rounded-[1.6rem] border border-[#d8c5a8]" />
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top,#fffaf2_0%,rgba(255,255,255,0)_38%),linear-gradient(135deg,rgba(154,116,65,0.12),rgba(255,255,255,0)_35%)]" />

        <div className="relative z-10">
         <ReportPage>
  <header className="mb-7 flex items-start justify-between gap-5 border-b border-[#dfcfb7] pb-5">
    <div className="flex items-center gap-3">
      <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#1f1711] text-[16px] font-black text-[#f5d8a7]">
        AL
      </div>

      <div>
        <p className="text-[11px] font-bold uppercase tracking-[0.22em] text-[#9a7441]">
          {labels.preliminary}
        </p>
        <h1 className="mt-1 text-[27px] font-black tracking-tight text-[#1c1713]">
          {labels.report}
        </h1>
        <p className="mt-1 text-[12px] font-medium text-[#745f4b]">
          {labels.subtitle}
        </p>
      </div>
    </div>

    <div className="text-end text-[11px] font-semibold leading-6 text-[#7b6653]">
      {reportId ? (
        <p>
          <span className="text-[#9a7441]">{labels.reportId}: </span>
          {reportId}
        </p>
      ) : null}
      <p>
        <span className="text-[#9a7441]">{labels.generatedAt}: </span>
        {dateText}
      </p>
    </div>
  </header>

  <section className="mb-6 text-center">
    <h2 className="mx-auto max-w-[650px] text-[25px] font-black leading-tight text-[#1e1712]">
      {cleanText(result.title)}
    </h2>
  </section>

  <section className="mb-6 grid grid-cols-[250px_1fr] gap-5">
    <div className="rounded-[1.4rem] border border-[#dfcfb7] bg-[#efe3d2] p-3">
      <p className="mb-2 text-[10px] font-black uppercase tracking-[0.18em] text-[#9a7441]">
        {labels.objectImage}
      </p>

      {imageUrl ? (
        <img
          src={imageUrl}
          alt={result.title || labels.objectImage}
          className="h-[240px] w-full rounded-[1rem] object-cover"
        />
      ) : (
        <div className="flex h-[240px] items-center justify-center rounded-[1rem] bg-[#d8c5a8] text-[12px] font-bold text-[#735b42]">
          {labels.noImage}
        </div>
      )}
    </div>

    <div className="grid gap-3">
      <InfoBlock label={labels.identification} value={result.lookup} />
      <div className="grid grid-cols-2 gap-3">
        <InfoBlock label={labels.period} value={result.timePeriod} />
        <InfoBlock label={labels.origin} value={result.origin} />
      </div>
      <div className="grid grid-cols-2 gap-3">
        <InfoBlock label={labels.material} value={result.material} />
        <InfoBlock label={labels.style} value={result.style} />
      </div>
      <InfoBlock label={labels.value} value={result.estimatedValue} strong />
    </div>
  </section>

  <section className="mb-6 grid grid-cols-2 gap-4">
    <InfoBlock label={labels.condition} value={result.condition} />
    <InfoBlock label={labels.authenticity} value={result.authenticity} />
  </section>

  <section className="rounded-[1.4rem] border border-[#dfcfb7] bg-white/70 p-5">
    <h3 className="mb-2 text-[12px] font-black uppercase tracking-[0.18em] text-[#9a7441]">
      {labels.priceReasoning}
    </h3>
    <p className="line-clamp-[8] text-[13px] font-medium leading-7 text-[#2a2119]">
      {cleanText(result.priceReasoning)}
    </p>
  </section>

  <div className="absolute bottom-7 left-7 right-7 flex items-center justify-between border-t border-[#dfcfb7] pt-3 text-[10px] font-semibold text-[#9a7441]/70">
    <span>{labels.generatedBy}</span>
    <span>1 / 2</span>
  </div>
</ReportPage>

<ReportPage>
  <header className="mb-7 flex items-center justify-between border-b border-[#dfcfb7] pb-5">
    <div>
      <p className="text-[11px] font-bold uppercase tracking-[0.22em] text-[#9a7441]">
        {labels.report}
      </p>
      <h2 className="mt-1 text-[24px] font-black text-[#1c1713]">
        {cleanText(result.title)}
      </h2>
    </div>

    <div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#1f1711] text-[14px] font-black text-[#f5d8a7]">
      AL
    </div>
  </header>

  <section className="mb-6 rounded-[1.4rem] border border-[#dfcfb7] bg-white/70 p-5">
    <h3 className="mb-2 text-[12px] font-black uppercase tracking-[0.18em] text-[#9a7441]">
      {labels.historicalContext}
    </h3>
    <p className="text-[13px] font-medium leading-7 text-[#2a2119]">
      {cleanText(result.history)}
    </p>
  </section>

  <section className="mb-6 grid grid-cols-2 gap-4">
    <ListSection title={labels.valueDrivers} items={result.valueDrivers} />
    <ListSection title={labels.valueReducers} items={result.valueReducers} />
  </section>

  <section className="mb-6 grid grid-cols-2 gap-4">
    <ListSection title={labels.neededPhotos} items={result.neededPhotos} />

    <div className="rounded-2xl border border-[#e7dccb] bg-white/65 p-5">
      <h3 className="mb-3 text-[12px] font-black uppercase tracking-[0.18em] text-[#9a7441]">
        {labels.confidence}
      </h3>

      <div className="mb-3 flex items-end gap-2">
        <span className="text-[38px] font-black leading-none text-[#9a5f18]">
          {typeof result.confidence === "number" ? result.confidence : "—"}
        </span>
        <span className="pb-1 text-[13px] font-bold text-[#745f4b]">/ 10</span>
      </div>

      <p className="text-[12px] font-medium leading-6 text-[#33251b]">
        {cleanText(result.confidenceNote)}
      </p>

      {result.followUpQuestion ? (
        <div className="mt-4 rounded-xl bg-[#f8f1e8] p-3">
          <p className="mb-1 text-[10px] font-black uppercase tracking-[0.16em] text-[#9a7441]">
            {labels.nextQuestion}
          </p>
          <p className="text-[12px] font-semibold leading-6 text-[#2a2119]">
            {result.followUpQuestion}
          </p>
        </div>
      ) : null}
    </div>
  </section>

  <footer className="absolute bottom-7 left-7 right-7 overflow-hidden rounded-[1.3rem] bg-[#1f1711] p-5 text-center text-[#f8ead5]">
    <p className="mb-1 text-[11px] font-black uppercase tracking-[0.22em] text-[#d6a45d]">
      {labels.disclaimerTitle}
    </p>
    <p className="mx-auto max-w-[650px] text-[11px] font-medium leading-6 text-[#f8ead5]/85">
      {result.disclaimer || getDefaultDisclaimer(locale)}
    </p>
    <div className="mt-4 flex items-center justify-between text-[10px] font-semibold text-[#d6a45d]/75">
      <span>{labels.generatedBy}</span>
      <span>2 / 2</span>
    </div>
  </footer>
</ReportPage>
        </div>
      </div>

      <style jsx global>{`
  @media print {
    html,
    body {
      margin: 0 !important;
      padding: 0 !important;
      background: white !important;
    }

    body * {
      visibility: hidden !important;
    }

    .report-print-area,
    .report-print-area * {
      visibility: visible !important;
    }

    .report-print-area {
      position: absolute !important;
      inset: 0 auto auto 0 !important;
      width: 210mm !important;
      margin: 0 !important;
      padding: 0 !important;
      border: none !important;
      background: white !important;
      overflow: visible !important;
    }

    .report-print-area .antique-report-document {
      width: 210mm !important;
      margin: 0 !important;
      border-radius: 0 !important;
      box-shadow: none !important;
      overflow: visible !important;
    }

    .report-print-area .report-page {
      width: 210mm !important;
      height: 297mm !important;
      page-break-after: always !important;
      break-after: page !important;
      margin: 0 !important;
      overflow: hidden !important;
    }

    .report-print-area .report-page:last-child {
      page-break-after: auto !important;
      break-after: auto !important;
    }

    @page {
      size: A4;
      margin: 0;
    }
  }
`}</style>
    </article>
  );
}