"use client";

import { normalizeEvaluationImages } from "./evaluationImages";

type Locale = "ar" | "en" | "ku" | "fr" | "hi" | "fa" | "tr" | "ru" | "es";

type ReportResult = {
  title?: string;
  itemType?: string;
  lookup?: string;
  timePeriod?: string;
  period?: string;
  origin?: string;
  material?: string;
  style?: string;
  condition?: string;
  authenticity?: string;
  estimatedValue?: string;
  priceRange?: string;
  priceReasoning?: string;
  history?: string;
  historicalReading?: string;
  safeInitialChecks?: string[];
  description?: string;
  metalValue?: {
    metal: "silver" | "gold" | "platinum" | "palladium" | "copper" | "unknown";
    weightGrams?: number;
    purityAssumption?: string;
    spotPricePerGramUsd?: number;
    meltValueUsdLow?: number;
    meltValueUsdMid?: number;
    meltValueUsdHigh?: number;
    note?: string;
    scenarios?: {
      label: "light" | "medium" | "heavy";
      labelAr: string;
      weightGrams: number;
      purityAssumption: string;
      meltValueUsdLow: number;
      meltValueUsdMid: number;
      meltValueUsdHigh: number;
      antiqueEstimateUsdLow: number;
      antiqueEstimateUsdHigh: number;
      note: string;
    }[];
  };
  valueDrivers?: string[];
  valueReducers?: string[];
  neededPhotos?: string[];
  followUpQuestion?: string;
  confidence?: number;
  confidenceNote?: string;
  disclaimer?: string;
  artistAttribution?: {
    possibleArtist: string;
    matchLevel: "high" | "medium" | "low";
    reasons: string[];
    notice: string;
    exhibitionContext?: string;
  } | null;
  markAnalysis?: {
    hasMark: boolean;
    markType:
      | "hallmark"
      | "signature"
      | "maker_mark"
      | "purity_mark"
      | "serial_number"
      | "unknown";
    visibleText?: string;
    symbolDescription?: string;
    locationOnObject?: string;
    clarity?: "clear" | "partial" | "unclear";
    possibleMeaning?: string;
    confidence?: "low" | "medium" | "high";
    needsCloseup?: boolean;
    referenceMatches?: {
      id: string;
      markText?: string;
      possibleMeaning?: string;
      confidenceNotes?: string;
    }[];
  } | null;
};

type AntiqueReportDocumentProps = {
  locale: Locale;
  result: ReportResult;
  reportImages?: string[];
  imageUrl?: string;
  imageUrls?: string[];
  reportId?: string;
  generatedAt?: string;
  variant?: "preview" | "print";
};

const REPORT_LABELS: Record<
  Locale,
  {
    report: string;
    subtitle: string;
    preliminary: string;
    objectImage: string;
    identification: string;
    period: string;
    origin: string;
    material: string;
    style: string;
    value: string;
    condition: string;
    authenticity: string;
    priceReasoning: string;
    historicalReading: string;
    historicalContext: string;
    valueDrivers: string;
    valueReducers: string;
    neededPhotos: string;
    confidence: string;
    nextQuestion: string;
    disclaimerTitle: string;
    generatedBy: string;
    reportId: string;
    generatedAt: string;
    noImage: string;
    page: string;
  }
> = {
  ar: {
    report: "تقرير تقييم تحفة",
    subtitle: "تقييم بصري أولي للقطع التراثية والتحف والمجوهرات",
    preliminary: "تقييم أولي",
    objectImage: "صورة القطعة",
    identification: "التعريف",
    period: "العمر / الحقبة",
    origin: "المنشأ المحتمل",
    material: "المادة",
    style: "الأسلوب",
    value: "السعر التقديري",
    condition: "الحالة",
    authenticity: "الأصالة",
    priceReasoning: "سبب التقييم السعري",
    historicalReading: "القراءة التاريخية المحتملة",
    historicalContext: "الوصف والتحليل",
    valueDrivers: "عوامل ترفع القيمة",
    valueReducers: "عوامل تقلل القيمة",
    neededPhotos: "صور مطلوبة للتأكيد",
    confidence: "",
    nextQuestion: "السؤال التالي",
    disclaimerTitle: "تنبيه مهم",
    generatedBy: "Generated by KISHIB",
    reportId: "رقم التقرير",
    generatedAt: "تاريخ الإنشاء",
    noImage: "لا توجد صورة",
    page: "صفحة",
  },
  en: {
    report: "Antique Evaluation Report",
    subtitle: "Preliminary visual assessment for antiques, heritage objects, and jewelry",
    preliminary: "Preliminary evaluation",
    objectImage: "Object image",
    identification: "Identification",
    period: "Period / age",
    origin: "Possible origin",
    material: "Material",
    style: "Style",
    value: "Estimated value",
    condition: "Condition",
    authenticity: "Authenticity",
    priceReasoning: "Price reasoning",
    historicalReading: "Possible historical reading",
    historicalContext: "Description and analysis",
    valueDrivers: "Value drivers",
    valueReducers: "Value reducers",
    neededPhotos: "Photos needed for verification",
    confidence: "",
    nextQuestion: "Next question",
    disclaimerTitle: "Important notice",
    generatedBy: "Generated by KISHIB",
    reportId: "Report ID",
    generatedAt: "Generated at",
    noImage: "No image available",
    page: "Page",
  },
  ku: {
    report: "ڕاپۆرتی هەڵسەنگاندنی ئانتیک",
    subtitle: "هەڵسەنگاندنی سەرەتایی بۆ شتومەکی کۆن و کولتووری",
    preliminary: "هەڵسەنگاندنی سەرەتایی",
    objectImage: "وێنەی شتەکە",
    identification: "ناساندن",
    period: "سەردەم / تەمەن",
    origin: "سەرچاوەی ئەگەری",
    material: "ماددە",
    style: "شێواز",
    value: "نرخی مەزەندەکراو",
    condition: "دۆخ",
    authenticity: "ڕەسەنایەتی",
    priceReasoning: "هۆکاری نرخدانان",
    historicalReading: "خوێندنەوەی مێژووییی ئەگەری",
    historicalContext: "وەسف و شیکردنەوە",
    valueDrivers: "هۆکارەکانی زیادبوونی بەها",
    valueReducers: "هۆکارەکانی کەمبوونی بەها",
    neededPhotos: "وێنەی پێویست بۆ پشتڕاستکردنەوە",
    confidence: "",
    nextQuestion: "پرسیاری دواتر",
    disclaimerTitle: "ئاگاداری گرنگ",
    generatedBy: "Generated by KISHIB",
    reportId: "ژمارەی ڕاپۆرت",
    generatedAt: "دروستکراوە لە",
    noImage: "هیچ وێنەیەک نییە",
    page: "لاپەڕە",
  },
  fr: {
    report: "Rapport d’évaluation d’antiquité",
    subtitle: "Évaluation visuelle préliminaire des antiquités et bijoux",
    preliminary: "Évaluation préliminaire",
    objectImage: "Image de l’objet",
    identification: "Identification",
    period: "Période / âge",
    origin: "Origine possible",
    material: "Matériau",
    style: "Style",
    value: "Valeur estimée",
    condition: "État",
    authenticity: "Authenticité",
    priceReasoning: "Justification du prix",
    historicalReading: "Lecture historique possible",
    historicalContext: "Description et analyse",
    valueDrivers: "Facteurs de valeur",
    valueReducers: "Facteurs réduisant la valeur",
    neededPhotos: "Photos nécessaires",
    confidence: "",
    nextQuestion: "Question suivante",
    disclaimerTitle: "Avis important",
    generatedBy: "Generated by KISHIB",
    reportId: "ID du rapport",
    generatedAt: "Généré le",
    noImage: "Aucune image disponible",
    page: "Page",
  },
  hi: {
    report: "प्राचीन वस्तु मूल्यांकन रिपोर्ट",
    subtitle: "प्राचीन, विरासत वस्तुओं और आभूषणों के लिए प्रारंभिक दृश्य मूल्यांकन",
    preliminary: "प्रारंभिक मूल्यांकन",
    objectImage: "वस्तु की छवि",
    identification: "पहचान",
    period: "काल / आयु",
    origin: "संभावित उत्पत्ति",
    material: "सामग्री",
    style: "शैली",
    value: "अनुमानित मूल्य",
    condition: "स्थिति",
    authenticity: "प्रामाणिकता",
    priceReasoning: "मूल्य का कारण",
    historicalReading: "संभावित ऐतिहासिक पढ़त",
    historicalContext: "विवरण और विश्लेषण",
    valueDrivers: "मूल्य बढ़ाने वाले कारक",
    valueReducers: "मूल्य घटाने वाले कारक",
    neededPhotos: "पुष्टि के लिए आवश्यक तस्वीरें",
    confidence: "",
    nextQuestion: "अगला प्रश्न",
    disclaimerTitle: "महत्वपूर्ण सूचना",
    generatedBy: "KISHIB द्वारा निर्मित",
    reportId: "रिपोर्ट आईडी",
    generatedAt: "बनाया गया",
    noImage: "कोई छवि उपलब्ध नहीं",
    page: "पृष्ठ",
  },
  fa: {
    report: "گزارش ارزیابی عتیقه",
    subtitle: "ارزیابی تصویری اولیه برای عتیقه‌ها، اشیای میراثی و جواهرات",
    preliminary: "ارزیابی اولیه",
    objectImage: "تصویر قطعه",
    identification: "شناسایی",
    period: "دوره / سن",
    origin: "منشأ احتمالی",
    material: "جنس",
    style: "سبک",
    value: "ارزش تخمینی",
    condition: "وضعیت",
    authenticity: "اصالت",
    priceReasoning: "دلیل قیمت",
    historicalReading: "خوانش تاریخی احتمالی",
    historicalContext: "توضیح و تحلیل",
    valueDrivers: "عوامل افزایش ارزش",
    valueReducers: "عوامل کاهش ارزش",
    neededPhotos: "تصاویر لازم برای بررسی",
    confidence: "",
    nextQuestion: "پرسش بعدی",
    disclaimerTitle: "توجه مهم",
    generatedBy: "تولید شده توسط KISHIB",
    reportId: "شناسه گزارش",
    generatedAt: "تاریخ تولید",
    noImage: "تصویری موجود نیست",
    page: "صفحه",
  },
  tr: {
    report: "Antika Değerlendirme Raporu",
    subtitle: "Antikalar, kültürel miras objeleri ve takılar için ön görsel değerlendirme",
    preliminary: "Ön değerlendirme",
    objectImage: "Objenin görseli",
    identification: "Tanımlama",
    period: "Dönem / yaş",
    origin: "Olası köken",
    material: "Malzeme",
    style: "Stil",
    value: "Tahmini değer",
    condition: "Durum",
    authenticity: "Özgünlük",
    priceReasoning: "Fiyat gerekçesi",
    historicalReading: "Olası tarihsel okuma",
    historicalContext: "Açıklama ve analiz",
    valueDrivers: "Değeri artıran etkenler",
    valueReducers: "Değeri azaltan etkenler",
    neededPhotos: "Doğrulama için gereken fotoğraflar",
    confidence: "",
    nextQuestion: "Sonraki soru",
    disclaimerTitle: "Önemli uyarı",
    generatedBy: "KISHIB tarafından oluşturuldu",
    reportId: "Rapor ID",
    generatedAt: "Oluşturulma tarihi",
    noImage: "Görsel yok",
    page: "Sayfa",
  },
  ru: {
    report: "Отчет об оценке антиквариата",
    subtitle: "Предварительная визуальная оценка антиквариата, предметов наследия и ювелирных изделий",
    preliminary: "Предварительная оценка",
    objectImage: "Изображение предмета",
    identification: "Идентификация",
    period: "Период / возраст",
    origin: "Возможное происхождение",
    material: "Материал",
    style: "Стиль",
    value: "Оценочная стоимость",
    condition: "Состояние",
    authenticity: "Подлинность",
    priceReasoning: "Обоснование цены",
    historicalReading: "Возможное историческое прочтение",
    historicalContext: "Описание и анализ",
    valueDrivers: "Факторы повышения стоимости",
    valueReducers: "Факторы снижения стоимости",
    neededPhotos: "Фото для проверки",
    confidence: "",
    nextQuestion: "Следующий вопрос",
    disclaimerTitle: "Важное уведомление",
    generatedBy: "Создано KISHIB",
    reportId: "ID отчета",
    generatedAt: "Дата создания",
    noImage: "Изображение недоступно",
    page: "Страница",
  },
  es: {
    report: "Informe de evaluación de antigüedad",
    subtitle: "Evaluación visual preliminar para antigüedades, objetos patrimoniales y joyería",
    preliminary: "Evaluación preliminar",
    objectImage: "Imagen del objeto",
    identification: "Identificación",
    period: "Período / edad",
    origin: "Origen posible",
    material: "Material",
    style: "Estilo",
    value: "Valor estimado",
    condition: "Estado",
    authenticity: "Autenticidad",
    priceReasoning: "Razón del precio",
    historicalReading: "Lectura histórica posible",
    historicalContext: "Descripción y análisis",
    valueDrivers: "Factores que aumentan el valor",
    valueReducers: "Factores que reducen el valor",
    neededPhotos: "Fotos necesarias para verificación",
    confidence: "",
    nextQuestion: "Siguiente pregunta",
    disclaimerTitle: "Aviso importante",
    generatedBy: "Generado por KISHIB",
    reportId: "ID del informe",
    generatedAt: "Generado el",
    noImage: "No hay imagen disponible",
    page: "Página",
  },};

function getDirection(locale: Locale) {
  return locale === "ar" || locale === "ku" || locale === "fa" ? "rtl" : "ltr";
}

function looksMojibake(value: string) {
  return /(?:\u00d8|\u00d9|\u00da|\u00db|\u00d0|\u00d1|\u00c3|\u00c2|\u00e0\u00a4|\u00e0\u00a5|Ã˜|Ã™|Ãš|Ã›|Ãƒ|Ã‚)/.test(value);
}

function mojibakeScore(value: string) {
  return (
    value.match(
      /(?:\u00d8|\u00d9|\u00da|\u00db|\u00d0|\u00d1|\u00c3|\u00c2|\u00e0\u00a4|\u00e0\u00a5|Ã˜|Ã™|Ãš|Ã›|Ãƒ|Ã‚)/g,
    )?.length || 0
  );
}

function repairMojibakeText(value: string): string {
  if (!looksMojibake(value)) return value;

  try {
    let best = value;
    let bestScore = mojibakeScore(value);

    for (let attempt = 0; attempt < 3; attempt += 1) {
      const bytes = Uint8Array.from(best, (char) => char.charCodeAt(0) & 0xff);
      const repaired = new TextDecoder("utf-8", { fatal: false }).decode(bytes);
      const score = mojibakeScore(repaired);

      if (score >= bestScore) break;

      best = repaired;
      bestScore = score;

      if (score === 0) break;
    }

    return best;
  } catch {
    return value;
  }
}

function repairLabels<T extends Record<string, string>>(labels: T): T {
  return Object.fromEntries(
    Object.entries(labels).map(([key, value]) => [key, repairMojibakeText(value)]),
  ) as T;
}
function cleanReportText(value?: string) {
  if (!value || !value.trim()) return "";

  const raw = value.trim();
  const repaired = repairMojibakeText(raw).trim();
  const candidate = repaired || raw;

  return /(?:Ø|Ù|Û|Ã|Â|Ð|Ñ|�)/.test(candidate) ? "" : candidate;
}

function compactReportText(value: string, maxLength = 170) {
  const cleanValue = cleanReportText(value);

  if (!cleanValue) return "";

  const firstSentence = cleanValue.split(/(?<=[.!؟])\s+/)[0] || cleanValue;

  if (firstSentence.length <= maxLength) return firstSentence;

  return `${firstSentence.slice(0, maxLength).trim()}...`;
}

function getDefaultDisclaimer(locale: Locale) {
  if (locale === "en") {
    return "This report is a preliminary visual evaluation based on the provided image and information. It is not an authenticity certificate, legal valuation, insurance appraisal, or auction guarantee.";
  }

  if (locale === "fr") {
    return "Ce rapport est une évaluation visuelle préliminaire basée sur l’image et les informations fournies. Il ne constitue pas un certificat d’authenticité, une expertise légale, une estimation d’assurance ou une garantie de vente aux enchères.";
  }

  if (locale === "ku") {
    return "ئەم ڕاپۆرتە هەڵسەنگاندنێکی سەرەتاییە بە پشتبەستن بە وێنە و زانیاریی پێشکەشکراو. ئەمە بڕوانامەی ڕەسەنایەتی، نرخدانانی یاسایی، هەڵسەنگاندنی بیمە، یان گەرەنتی مزایدە نییە.";
  }

  return "هذا التقرير هو تقييم بصري أولي بالاعتماد على الصورة والمعلومات المقدمة. لا يُعد شهادة أصالة، أو تخميناً قانونياً، أو تقييماً تأمينياً، أو ضماناً للبيع في المزاد.";
}

function formatDate(locale: Locale, generatedAt?: string) {
  if (generatedAt) return generatedAt;

  const dateLocale =
    locale === "ar" ? "ar-IQ" : locale === "fr" ? "fr-FR" : "en-US";

  return new Intl.DateTimeFormat(dateLocale, {
    year: "numeric",
    month: "short",
    day: "2-digit",
  }).format(new Date());
}

/*
function InfoBlock({
  label,
  value,
  strong = false,
}: {
  label: string;
  value?: string;
  strong?: boolean;
}) {
  const cleanValue = cleanReportText(value);

  if (!cleanValue) return null;

  return (
    <div className="rounded-[14px] border border-[#e5d4ba] bg-white/64 p-3">
      <p className="mb-1 text-[8.5px] font-black uppercase tracking-[0.14em] text-[#9a7441]">
        {label}
      </p>
      <p
        className={[
          "whitespace-pre-line break-words leading-[1.65] text-[#241b14]",
          strong
            ? "text-[13.5px] font-black text-[#9a5f18]"
            : "text-[11.2px] font-semibold",
        ].join(" ")}
      >
        {cleanValue}
      </p>
    </div>
  );
}

function TextBox({
  title,
  body,
  compact = false,
}: {
  title: string;
  body?: string;
  compact?: boolean;
}) {
  const cleanBody = cleanReportText(body);

  if (!cleanBody) return null;

  return (
    <section className="rounded-[16px] border border-[#e5d4ba] bg-white/64 p-4">
      <h3 className="mb-2 text-[9px] font-black uppercase tracking-[0.16em] text-[#9a7441]">
        {title}
      </h3>
      <p
        className={[
          "whitespace-pre-line break-words font-semibold text-[#2a2119]",
          compact ? "text-[10.2px] leading-[1.72]" : "text-[11px] leading-[1.82]",
        ].join(" ")}
      >
        {cleanBody}
      </p>
    </section>
  );
}

function HistoricalReadingBox({
  title,
  body,
}: {
  title: string;
  body?: string;
}) {
  const cleanBody = cleanReportText(body);

  if (!cleanBody) return null;

  return (
    <section className="rounded-[14px] border-y border-[#e5d4ba] bg-[#fff8ee]/72 px-4 py-3">
      <h3 className="mb-1.5 text-[8.8px] font-black uppercase tracking-[0.16em] text-[#9a7441]">
        {title}
      </h3>
      <p className="whitespace-pre-line text-[10.6px] font-semibold leading-[1.75] text-[#6f5b47]">
        {cleanBody}
      </p>
    </section>
  );
}

function getSafeInitialChecksReportCopy(locale: Locale) {
  if (locale === "en") {
    return {
      title: "Safe Initial Checks",
      note: "These checks do not prove authenticity, but they can help you collect clearer information before expert inspection.",
    };
  }

  if (locale === "fr") {
    return {
      title: "Vérifications initiales sûres",
      note: "Ces vérifications ne prouvent pas l’authenticité, mais elles peuvent aider à collecter des informations plus claires avant l’examen d’un spécialiste.",
    };
  }

  if (locale === "hi") {
    return {
      title: "सुरक्षित प्रारंभिक जाँच",
      note: "ये जाँचें प्रामाणिकता को अंतिम रूप से सिद्ध नहीं करतीं, लेकिन विशेषज्ञ जाँच से पहले स्पष्ट जानकारी जुटाने में मदद कर सकती हैं.",
    };
  }

  if (locale === "fa") {
    return {
      title: "بررسی‌های اولیه ایمن",
      note: "این بررسی‌ها اصالت را به‌طور قطعی ثابت نمی‌کنند، اما می‌توانند پیش از بررسی تخصصی به گردآوری اطلاعات روشن‌تر کمک کنند.",
    };
  }

  if (locale === "tr") {
    return {
      title: "Güvenli ilk kontroller",
      note: "Bu kontroller özgünlüğü kesin olarak kanıtlamaz, ancak uzman incelemesinden önce daha net bilgi toplamanıza yardımcı olabilir.",
    };
  }

  if (locale === "ru") {
    return {
      title: "Безопасные первичные проверки",
      note: "Эти проверки не доказывают подлинность окончательно, но помогают собрать более ясную информацию перед экспертным осмотром.",
    };
  }

  if (locale === "ku") {
    return {
      title: "پشکنینی سەرەتاییی ئارام",
      note: "ئەم پشکنینانە ڕەسەنایەتی بە شێوەی کۆتایی ناسەلمێنن، بەڵام دەتوانن پێش پشکنینی پسپۆڕ زانیاریی ڕوونتر کۆبکەنەوە.",
    };
  }

  return {
    title: "فحوصات أولية آمنة",
    note: "هذه الفحوصات لا تثبت الأصالة نهائيًا، لكنها تساعدك على جمع معلومات أوضح قبل الفحص المختص.",
  };
}

function SafeInitialChecksBox({
  title,
  note,
  items,
}: {
  title: string;
  note: string;
  items?: string[];
}) {
  const safeItems = Array.isArray(items)
    ? items.map((item) => compactReportText(item, 110)).filter(Boolean).slice(0, 7)
    : [];

  if (safeItems.length === 0) return null;

  return (
    <section className="rounded-[14px] border-y border-[#e5d4ba] bg-[#fff8ee]/70 px-4 py-3">
      <h3 className="mb-2 text-[8.8px] font-black uppercase tracking-[0.16em] text-[#9a7441]">
        {title}
      </h3>

      <div className="grid gap-1.5">
        {safeItems.map((item, index) => (
          <div
            key={`${title}-${index}`}
            className="flex gap-2 text-[10.2px] font-semibold leading-[1.62] text-[#6f5b47]"
          >
            <span className="mt-[7px] h-1.5 w-1.5 shrink-0 rounded-full bg-[#c79a54]" />
            <span>{item}</span>
          </div>
        ))}
      </div>

      <p className="mt-2 text-[8.8px] font-semibold leading-[1.55] text-[#8a735c]">
        {note}
      </p>
    </section>
  );
}

function ListSection({
  title,
  items,
}: {
  title: string;
  items?: string[];
}) {
  const safeItems = Array.isArray(items)
    ? items.map((item) => cleanReportText(item)).filter(Boolean)
    : [];

  if (safeItems.length === 0) return null;

  if (safeItems.length === 0) {
    return <TextBox title={title} body="—" compact />;
  }

  return (
    <section className="rounded-[16px] border border-[#e5d4ba] bg-white/64 p-4">
      <h3 className="mb-2 text-[9px] font-black uppercase tracking-[0.16em] text-[#9a7441]">
        {title}
      </h3>

      <div className="grid gap-1.5">
        {safeItems.map((item, index) => (
          <div
            key={`${title}-${index}`}
            className="flex gap-2 rounded-[10px] bg-[#f8f1e8] px-2.5 py-1.5 text-[10.2px] font-semibold leading-[1.62] text-[#33251b]"
          >
            <span className="mt-[2px] flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-[#2a2119] text-[8px] text-[#f5d8a7]">
              {index + 1}
            </span>
            <span className="break-words">{item}</span>
          </div>
        ))}
      </div>
    </section>
  );
}

function MarkReportSection({
  locale,
  mark,
}: {
  locale: Locale;
  mark: ReportResult["markAnalysis"];
}) {
  if (!mark?.hasMark) return null;

  const visibleText = cleanReportText(mark.visibleText);
  const symbolDescription = cleanReportText(mark.symbolDescription);
  const locationOnObject = cleanReportText(mark.locationOnObject);
  const possibleMeaning = cleanReportText(mark.possibleMeaning);
  const referenceMatches =
    mark.referenceMatches
      ?.map((match) =>
        [
          cleanReportText(match.markText),
          cleanReportText(match.possibleMeaning),
        ]
          .filter(Boolean)
          .join(" — "),
      )
      .filter(Boolean)
      .slice(0, 2) || [];

  if (
    !visibleText &&
    !symbolDescription &&
    !locationOnObject &&
    !possibleMeaning &&
    referenceMatches.length === 0
  ) {
    return null;
  }

  const title = locale === "en" ? "Mark or signature" : "الختم أو التوقيع";
  const caution =
    locale === "en"
      ? "Visual clue only. It does not prove authenticity, maker, material, or purity without close-up verification and direct inspection."
      : "إشارة بصرية فقط، ولا تثبت الأصالة أو الصانع أو المادة أو العيار دون صورة مقرّبة وفحص مباشر.";
  const rows = [
    visibleText ? `${locale === "en" ? "Visible text" : "النص الظاهر"}: ${visibleText}` : "",
    symbolDescription
      ? `${locale === "en" ? "Description" : "الوصف"}: ${symbolDescription}`
      : "",
    locationOnObject
      ? `${locale === "en" ? "Location" : "المكان"}: ${locationOnObject}`
      : "",
    possibleMeaning
      ? `${locale === "en" ? "Possible meaning" : "المعنى المحتمل"}: ${possibleMeaning}`
      : "",
    ...referenceMatches.map(
      (match) => `${locale === "en" ? "Reference hint" : "إشارة مرجعية"}: ${match}`,
    ),
    caution,
  ].filter(Boolean);

  return <ListSection title={title} items={rows} />;
}

function ReportPage({
  children,
  pageNumber,
  labels,
}: {
  children: React.ReactNode;
  pageNumber: string;
  labels: { generatedBy: string; page: string };
}) {
  return (
    <div className="report-page relative min-h-[1123px] w-[794px] shrink-0 overflow-visible bg-[#f7f0e6] p-[28px]">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top,#fffaf2_0%,rgba(255,255,255,0)_36%),linear-gradient(135deg,rgba(154,116,65,0.12),rgba(255,255,255,0)_35%)]" />

      <div className="relative z-10 min-h-[1067px] pb-8">
        {children}

        <div className="absolute bottom-0 left-0 right-0 flex items-center justify-between border-t border-[#dfcfb7] pt-2 text-[9px] font-bold text-[#9a7441]/70">
          <span>{labels.generatedBy}</span>
          <span>
            {labels.page} {pageNumber}
          </span>
        </div>
      </div>
    </div>
  );
}

function ReportLine({
  label,
  value,
  strong = false,
}: {
  label: string;
  value?: string;
  strong?: boolean;
}) {
  const cleanValue = cleanReportText(value);
  if (!cleanValue) return null;

  return (
    <div className="min-w-0">
      <p className="text-[8.5px] font-black uppercase tracking-[0.14em] text-[#9a7441]">
        {label}
      </p>
      <p
        className={[
          "mt-1 whitespace-pre-line break-words leading-[1.8]",
          strong
            ? "text-[13px] font-black text-[#9a5f18]"
            : "text-[9.5px] font-semibold text-[#2a2119]",
        ].join(" ")}
      >
        {cleanValue}
      </p>
    </div>
  );
}

function ReportTextSection({ title, body }: { title: string; body?: string }) {
  const cleanBody = cleanReportText(body);
  if (!cleanBody) return null;

  return (
    <section className="border-b border-[#dfcfb7] pb-3">
      <h3 className="mb-2 text-[9px] font-black uppercase tracking-[0.16em] text-[#9a7441]">
        {title}
      </h3>
      <p className="whitespace-pre-line break-words text-[9.5px] font-semibold leading-[1.65] text-[#2a2119]">
        {cleanBody}
      </p>
    </section>
  );
}
*/

type ReportData = {
  labels: (typeof REPORT_LABELS)[Locale];
  dir: "rtl" | "ltr";
  dateText: string;
  title: string;
  images: string[];
  primaryImage?: string;
  itemType: string;
  period: string;
  origin: string;
  material: string;
  value: string;
  condition: string;
  authenticity: string;
  lookup: string;
  description: string;
  historicalReading: string;
  priceReasoning: string;
  disclaimer: string;
  reportId?: string;
};

function normalizeReportImages(result: ReportResult, imageUrl?: string, imageUrls: string[] = []) {
  if (imageUrls.length > 0) return normalizeEvaluationImages({ imageUrls });

  return normalizeEvaluationImages({
    ...(result as ReportResult & {
      imageUrl?: string;
      imageUrls?: string[];
      uploadedImageUrls?: string[];
      imagePreview?: string;
      imagePreviews?: string[];
      originalImage?: string;
      originalImages?: string[];
      uploadedImageUrl?: string;
      sourceImageUrl?: string;
    }),
    imageUrl:
      (result as { imageUrl?: string }).imageUrl || imageUrl,
  });
}

function buildReportData({
  locale,
  result,
  reportImages,
  imageUrl,
  imageUrls = [],
  reportId,
  generatedAt,
}: AntiqueReportDocumentProps): ReportData {
  const labels = repairLabels(REPORT_LABELS[locale] || REPORT_LABELS.ar);
  const value = result.estimatedValue || result.priceRange || "";
  const description = result.history || result.description || "";
  const images = reportImages?.length
    ? reportImages
    : normalizeReportImages(result, imageUrl, imageUrls);

  return {
    labels,
    dir: getDirection(locale),
    dateText: formatDate(locale, generatedAt),
    title: cleanReportText(result.title || result.itemType) || "KISHIB Evaluation",
    images,
    primaryImage: images[0],
    itemType: cleanReportText(result.itemType || result.lookup),
    period: cleanReportText(result.timePeriod || result.period),
    origin: cleanReportText(result.origin),
    material: cleanReportText(result.material),
    value: cleanReportText(value),
    condition: cleanReportText(result.condition),
    authenticity: cleanReportText(result.authenticity),
    lookup: cleanReportText(result.lookup),
    description: cleanReportText(description),
    historicalReading: cleanReportText(result.historicalReading),
    priceReasoning: cleanReportText(result.priceReasoning),
    disclaimer: cleanReportText(result.disclaimer) || getDefaultDisclaimer(locale),
    reportId,
  };
}

/*
function ReportImageGallery({
  images,
  title,
  primaryAlt,
}: {
  images: string[];
  title: string;
  primaryAlt: string;
}) {
  const galleryImages = images.slice(1, 7);

  if (images.length === 0) return null;

  return (
    <section className="border-b border-[#dfcfb7] pb-4">
      <p className="mb-2 text-[9px] font-black uppercase tracking-[0.16em] text-[#9a7441]">
        {title}
      </p>
      {images[0] ? (
        <div className="flex h-[340px] items-center justify-center rounded-[18px] border border-[#dfcfb7] bg-[#efe3d2] p-3">
          <img
            src={images[0]}
            alt={primaryAlt}
            className="max-h-full max-w-full rounded-[12px] object-contain"
          />
        </div>
      ) : null}

      {galleryImages.length > 0 ? (
        <div className="mt-3 grid grid-cols-3 gap-3">
          {galleryImages.map((src, index) => (
            <div
              key={`${src}-${index}`}
              className="flex aspect-[4/3] items-center justify-center rounded-[12px] border border-[#dfcfb7] bg-[#f8f0e5] p-2"
            >
              <img
                src={src}
                alt={`${primaryAlt} ${index + 2}`}
                className="max-h-full max-w-full rounded-[8px] object-contain"
              />
            </div>
          ))}
        </div>
      ) : null}
    </section>
  );
}
*/

function ShareInfoLine({ label, value }: { label: string; value: string }) {
  if (!value) return null;

  return (
    <div className="border-b border-[#d2b98f]/55 pb-4 last:border-b-0">
      <p className="text-[20px] font-black uppercase tracking-[0.12em] text-[#9a7441]">
        {label}
      </p>
      <p className="mt-1 text-[30px] font-black leading-tight text-[#241913]">
        {value}
      </p>
    </div>
  );
}

function ShareImageStrip({ images, alt }: { images: string[]; alt: string }) {
  const extras = images.slice(1, 3);
  if (!extras.length) return null;

  return (
    <div className="mt-4 flex max-h-[104px] gap-3 overflow-hidden">
      {extras.map((src, index) => (
        <figure
          key={`${src}-${index}`}
          className="flex h-[104px] w-[104px] shrink-0 items-center justify-center overflow-hidden border border-[#d2b98f]/60 bg-[#f8f0e5]/45"
        >
          <img src={src} alt={`${alt} ${index + 2}`} className="max-h-full max-w-full object-contain" />
        </figure>
      ))}
    </div>
  );
}

function ShareTextBlock({ title, body }: { title: string; body: string }) {
  if (!body) return null;

  return (
    <section className="border-t border-[#d2b98f]/60 pt-4">
      <h3 className="text-[20px] font-black uppercase tracking-[0.12em] text-[#9a7441]">
        {title}
      </h3>
      <p className="mt-2 break-words text-[25px] font-bold leading-[1.48] text-[#2a2119]">
        {body}
      </p>
    </section>
  );
}

function ShareReportTemplate({
  locale,
  result,
  reportImages,
  imageUrl,
  imageUrls = [],
  reportId,
  generatedAt,
}: AntiqueReportDocumentProps) {
  const data = buildReportData({ locale, result, reportImages, imageUrl, imageUrls, reportId, generatedAt });
  const summary = compactReportText(
    data.lookup || data.description || data.priceReasoning,
    180,
  );
  const details = [
    { title: data.labels.identification, body: data.lookup },
    { title: data.labels.historicalContext, body: data.description },
    { title: data.labels.authenticity, body: data.authenticity },
    { title: data.labels.priceReasoning, body: data.priceReasoning },
  ].filter((item) => item.body);
  const meta = [
    { label: data.labels.value, value: data.value },
    { label: data.labels.material, value: data.material },
    { label: data.labels.period, value: data.period },
    { label: data.labels.authenticity, value: data.authenticity },
  ].filter((item) => item.value).slice(0, 4);

  return (
    <article
      dir={data.dir}
      className="antique-report-document kishib-share-template report-share-story h-[1920px] w-[1080px] overflow-hidden bg-[#f4eadc] text-[#241913]"
    >
      <div className="relative flex h-full w-full flex-col px-[72px] py-[86px]">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top,#fffaf2_0%,rgba(255,255,255,0)_42%),linear-gradient(135deg,rgba(138,79,50,0.16),rgba(255,255,255,0)_38%)]" />
        <header className="relative z-10 flex items-center justify-between gap-6 border-b border-[#d2b98f]/70 pb-8">
          <div className="flex items-center gap-5">
            <img src="/brand/aaa.png" alt="KISHIB" className="h-20 w-20 object-contain" />
            <div>
              <p className="text-[28px] font-black tracking-[0.18em] text-[#8A4F32]">KISHIB</p>
              <p className="text-[24px] font-bold text-[#735f4b]">{data.labels.preliminary}</p>
            </div>
          </div>
          <p className="text-[20px] font-bold text-[#9a7441]">{data.dateText}</p>
        </header>

        <section className="relative z-10 mt-8">
          <h2 className={[
            "line-clamp-3 break-words font-black leading-[1.08] text-[#1e1712]",
            "text-[64px]",
          ].join(" ")}>
            {data.title}
          </h2>
        </section>

        <section className="relative z-10 mt-8 grid grid-cols-[minmax(0,1.58fr)_minmax(0,1fr)] gap-9 border-y border-[#d2b98f]/70 py-7">
          <div className="grid content-start gap-5">
            {meta.map((item) => (
              <ShareInfoLine key={item.label} label={item.label} value={item.value} />
            ))}
          </div>

          <div className="flex min-h-[420px] flex-col items-center justify-start">
            {data.primaryImage ? (
              <img src={data.primaryImage} alt={data.title} className="max-h-[420px] w-full object-contain" />
            ) : (
              <p className="pt-24 text-[34px] font-bold text-[#735f4b]">{data.labels.noImage}</p>
            )}
            <ShareImageStrip images={data.images} alt={data.title} />
          </div>
        </section>

        {summary ? (
          <p className="relative z-10 mt-6 break-words border-b border-[#d2b98f]/60 pb-5 text-[32px] font-bold leading-[1.45] text-[#4d3d30]">
            {summary}
          </p>
        ) : null}

        <section className="relative z-10 mt-5 grid gap-5">
          {details.slice(0, 3).map((item) => (
            <ShareTextBlock key={item.title} title={item.title} body={item.body} />
          ))}
        </section>

        <footer className="relative z-10 mt-auto flex items-center justify-between border-t border-[#d2b98f]/70 pt-7">
          <span className="text-[24px] font-black uppercase tracking-[0.16em] text-[#8A4F32]">
            {data.labels.generatedBy}
          </span>
          {data.reportId ? (
            <span className="text-[20px] font-bold text-[#735f4b]">{data.reportId}</span>
          ) : null}
        </footer>
      </div>
    </article>
  );
}

export default function AntiqueReportDocument({
  locale,
  result,
  reportImages,
  imageUrl,
  imageUrls = [],
  reportId,
  generatedAt,
  variant = "preview",
}: AntiqueReportDocumentProps) {
  return (
    <ShareReportTemplate
      locale={locale}
      result={result}
      reportImages={reportImages}
      imageUrl={imageUrl}
      imageUrls={imageUrls}
      reportId={reportId}
      generatedAt={generatedAt}
      variant={variant}
    />
  );

  /*
  const labels = repairLabels(REPORT_LABELS[locale] || REPORT_LABELS.ar);
  const safeInitialChecksCopy = getSafeInitialChecksReportCopy(locale);
  const dir = getDirection(locale);
  const dateText = formatDate(locale, generatedAt);

  const period = result.timePeriod || result.period;
  const value = result.estimatedValue || result.priceRange;
  const reportImages = normalizeReportImages(result, imageUrl, imageUrls);
  const primaryImage = reportImages[0];
  const cleanTitle = cleanReportText(result.title) || "KISHIB Evaluation";
  const metalValue = result.metalValue;
  const showPreciousMetalEstimate =
    metalValue?.metal === "gold" || metalValue?.metal === "silver";
  const reportText = {
    name: locale === "ar" ? "الاسم" : "Name",
    itemType: locale === "ar" ? "نوع القطعة" : "Object type",
    age: locale === "ar" ? "العمر" : "Age",
    period: locale === "ar" ? "الحقبة" : "Period",
    description: locale === "ar" ? "الوصف والتحليل" : "Description and analysis",
    metalEstimate: locale === "ar" ? "تخمينات قيمة المعدن" : "Metal value estimates",
    weight: locale === "ar" ? "الوزن المفترض" : "Assumed weight",
    rawValue: locale === "ar" ? "قيمة المعدن الخام" : "Raw metal value",
    antiqueValue: locale === "ar" ? "مع قيمة الأنتيك" : "With antique value",
  };
  const priceReason = compactReportText(
    result.priceReasoning || result.description || result.history || value || "",
    260,
  );
  const valueDrivers = (result.valueDrivers || [])
    .map((item) => compactReportText(item, 105))
    .filter(Boolean)
    .slice(0, 4);
  const valueReducers = (result.valueReducers || [])
    .map((item) => compactReportText(item, 105))
    .filter(Boolean)
    .slice(0, 4);
  const safeInitialChecks = (result.safeInitialChecks || [])
    .map((item) => compactReportText(item, 110))
    .filter(Boolean)
    .slice(0, 7);

  return (
    <article
      dir={dir}
      className={[
        "antique-report-document mx-auto text-[#211a15]",
        variant === "print"
          ? "w-[794px]"
          : "w-full max-w-[794px] overflow-visible",
      ].join(" ")}
    >
      <div className={variant === "print" ? "" : "space-y-6"}>
        <ReportPage pageNumber="1 / 1" labels={labels}>
          <header className="mb-3 flex items-start justify-between gap-4 border-b border-[#dfcfb7] pb-3">
            <div className="flex items-center gap-3">
              <div className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden">
                <img
                  src="/brand/aaa.png"
                  alt="KISHIB"
                  className="h-full w-full object-contain"
                />
              </div>

              <div>
                <p className="text-[9px] font-black uppercase tracking-[0.22em] text-[#9a7441]">
                  {labels.preliminary}
                </p>
                <h1 className="mt-0.5 text-[19px] font-black leading-tight tracking-tight text-[#1c1713]">
                  KISHIB Report
                </h1>
              </div>
            </div>

            <div className="max-w-[220px] text-end text-[9.5px] font-bold leading-5 text-[#7b6653]">
              {reportId ? (
                <p>
                  <span className="text-[#9a7441]">{labels.reportId}: </span>
                  {reportId}
                </p>
              ) : null}
              <p>
                <span className="text-[#9a7441]">{labels.generatedAt}: </span>
                {dateText}
              </p>
            </div>
          </header>

          <div className="space-y-3 text-[10px] leading-[1.65]">
            <section className="border-b border-[#dfcfb7] pb-3">
              <p className="text-[9px] font-black uppercase tracking-[0.16em] text-[#9a7441]">
                {reportText.name}
              </p>
              <h2 className="mt-1 break-words text-[20px] font-black leading-[1.3] text-[#1e1712]">
                {cleanTitle}
              </h2>
            </section>

            <ReportImageGallery
              images={reportImages}
              title={labels.objectImage}
              primaryAlt={cleanTitle}
            />

            <section className="grid grid-cols-2 gap-x-7 gap-y-2.5 border-b border-[#dfcfb7] pb-3">
              <ReportLine label={reportText.itemType} value={result.itemType} />
              <ReportLine label={labels.origin} value={result.origin} />
              <ReportLine label={reportText.age} value={result.timePeriod} />
              {result.period && result.period !== result.timePeriod ? (
                <ReportLine label={reportText.period} value={result.period} />
              ) : null}
              <ReportLine label={labels.value} value={value} strong />
            </section>

            <ReportTextSection title={labels.identification} body={result.lookup} />
            <ReportTextSection
              title={reportText.description}
              body={result.history || result.description}
            />
            <ReportTextSection
              title={labels.historicalReading}
              body={result.historicalReading}
            />
            <ReportTextSection
              title={labels.authenticity}
              body={result.authenticity}
            />
            <ReportTextSection title={labels.priceReasoning} body={result.priceReasoning} />

            {safeInitialChecks.length > 0 ? (
              <SafeInitialChecksBox
                title={safeInitialChecksCopy.title}
                note={safeInitialChecksCopy.note}
                items={safeInitialChecks}
              />
            ) : null}

            <section className="grid grid-cols-2 gap-3">
              <ListSection title={labels.valueDrivers} items={valueDrivers} />
              <ListSection title={labels.valueReducers} items={valueReducers} />
            </section>

            <MarkReportSection locale={locale} mark={result.markAnalysis} />

            <ReportTextSection
              title={labels.disclaimerTitle}
              body={result.disclaimer || getDefaultDisclaimer(locale)}
            />

            {showPreciousMetalEstimate && metalValue ? (
              <section className="border-t border-[#dfcfb7] pt-5">
                <h3 className="mb-3 text-[11px] font-black text-[#9a7441]">
                  {reportText.metalEstimate}
                </h3>
                {metalValue!.scenarios?.length ? (
                  <div className="divide-y divide-[#dfcfb7] border-y border-[#dfcfb7]">
                    {metalValue!.scenarios!.map((scenario) => (
                      <div key={scenario.label} className="grid grid-cols-3 gap-4 py-3">
                        <ReportLine
                          label={reportText.weight}
                          value={`${locale === "ar" ? scenario.labelAr : scenario.label} · ${scenario.weightGrams}g`}
                        />
                        <ReportLine label={reportText.rawValue} value={`$${scenario.meltValueUsdMid}`} />
                        <ReportLine
                          label={reportText.antiqueValue}
                          value={`$${scenario.antiqueEstimateUsdLow} - $${scenario.antiqueEstimateUsdHigh}`}
                        />
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="grid grid-cols-2 gap-x-8 gap-y-4 border-y border-[#dfcfb7] py-3">
                    <ReportLine label={reportText.itemType} value={metalValue!.metal} />
                    <ReportLine
                      label={reportText.weight}
                      value={metalValue!.weightGrams ? `${metalValue!.weightGrams}g` : undefined}
                    />
                    <ReportLine
                      label={reportText.rawValue}
                      value={metalValue!.meltValueUsdLow && metalValue!.meltValueUsdHigh
                        ? `$${metalValue!.meltValueUsdLow} - $${metalValue!.meltValueUsdHigh}`
                        : undefined}
                    />
                  </div>
                )}
                {metalValue!.note ? (
                  <p className="mt-3 whitespace-pre-line break-words text-[10px] text-[#665442]">
                    {cleanReportText(metalValue!.note)}
                  </p>
                ) : null}
              </section>
            ) : null}
          </div>

          <div className="hidden" aria-hidden="true">
          <section className="mb-4 text-center">
            <h2 className="mx-auto max-w-[670px] break-words text-[24px] font-black leading-[1.25] text-[#1e1712]">
              {cleanTitle}
            </h2>
          </section>

          <section className="report-main-grid mb-4 grid grid-cols-[315px_1fr] gap-4">
            <div className="rounded-[16px] border border-[#dfcfb7] bg-[#efe3d2] p-3">
              {primaryImage ? (
                <div className="flex h-[330px] items-center justify-center rounded-[12px] bg-[#1f1711] p-2">
                  <img
                    src={primaryImage}
                    alt={cleanTitle || labels.objectImage}
                    className="max-h-full max-w-full rounded-[10px] object-contain"
                  />
                </div>
              ) : (
                <div className="flex h-[330px] items-center justify-center rounded-[12px] bg-[#d8c5a8] text-[11px] font-bold text-[#735b42]">
                  {labels.noImage}
                </div>
              )}
            </div>

            <div className="grid content-start gap-3">
              <InfoBlock label={labels.value} value={value} strong />

              <div className="grid grid-cols-2 gap-3">
                <InfoBlock label={labels.period} value={compactReportText(period || "", 95)} />
                <InfoBlock label={labels.material} value={compactReportText(result.material || "", 95)} />
                <InfoBlock label={labels.condition} value={compactReportText(result.condition || "", 120)} />
                <InfoBlock label={labels.authenticity} value={compactReportText(result.authenticity || "", 120)} />
              </div>
            </div>
          </section>

          {result.artistAttribution ? (
            <section className="mb-4 rounded-[14px] border border-[#dfcfb7] bg-[#f8f0e5] p-3">
              <p className="text-[9px] font-black uppercase tracking-[0.18em] text-[#9a7441]">
                {locale === "ar" ? "نسبة الفنان المحتملة" : "Potential artist attribution"}
              </p>
              <p className="mt-2 text-[11px] font-bold text-[#1e1712]">
                {locale === "ar" ? "الفنان المحتمل: " : "Potential artist: "}{result.artistAttribution.possibleArtist}
              </p>
              {result.artistAttribution.reasons.length ? (
                <p className="mt-1 text-[10px] leading-5 text-[#665442]">
                  {result.artistAttribution.reasons.join("، ")}
                </p>
              ) : null}
              <p className="mt-2 text-[9.5px] leading-5 text-[#7b6653]">{result.artistAttribution.notice}</p>
            </section>
          ) : null}

          <section className="mb-4">
            <HistoricalReadingBox
              title={labels.historicalReading}
              body={result.historicalReading}
            />
          </section>

          {safeInitialChecks.length > 0 ? (
            <section className="mb-4">
              <SafeInitialChecksBox
                title={safeInitialChecksCopy.title}
                note={safeInitialChecksCopy.note}
                items={safeInitialChecks}
              />
            </section>
          ) : null}

          <section className="mb-4">
            <TextBox title={labels.priceReasoning} body={priceReason} compact />
          </section>

          <section className="report-two-grid mb-4 grid grid-cols-2 gap-3">
            <ListSection title={labels.valueDrivers} items={valueDrivers} />
            <ListSection title={labels.valueReducers} items={valueReducers} />
          </section>
          </div>
        </ReportPage>
      </div>

      <style jsx global>{`
        .antique-report-document,
        .antique-report-document * {
          box-sizing: border-box;
        }

        .report-page {
          page-break-after: auto;
          break-after: auto;
        }

        @media print {
          html,
          body {
            width: 794px !important;
            margin: 0 !important;
            padding: 0 !important;
            background: white !important;
            overflow: visible !important;
          }

          body * {
            visibility: hidden !important;
          }

          .report-print-area,
          .report-print-area * {
            visibility: visible !important;
          }

          .report-print-area {
            display: block !important;
            position: static !important;
            inset: auto !important;
            box-sizing: border-box !important;
            width: 794px !important;
            height: auto !important;
            margin: 0 !important;
            padding: 0 !important;
            border: none !important;
            background: white !important;
            overflow: visible !important;
            opacity: 1 !important;
            pointer-events: auto !important;
          }

          .report-print-area .antique-report-document {
            width: 794px !important;
            max-width: none !important;
            margin: 0 !important;
            border-radius: 0 !important;
            box-shadow: none !important;
            overflow: visible !important;
          }

          .report-print-area .report-page {
            width: 794px !important;
            height: auto !important;
            min-height: 0 !important;
            margin: 0 !important;
            padding: 0 !important;
            overflow: visible !important;
            page-break-after: auto !important;
            break-after: auto !important;
            page-break-before: auto !important;
            break-before: auto !important;
          }

          .report-print-area .report-page > .relative {
            height: auto !important;
            min-height: 0 !important;
            padding-bottom: 8mm !important;
          }

          .report-print-area .report-page footer,
          .report-print-area .report-page > .relative > div:last-child {
            position: static !important;
            margin-top: 5mm !important;
          }

          .report-print-area .report-page header,
          .report-print-area .report-page section,
          .report-print-area .report-page footer,
          .report-print-area .report-page img {
            break-inside: avoid !important;
            page-break-inside: avoid !important;
          }

          .report-print-area .report-page + .report-page {
            page-break-before: always !important;
            break-before: page !important;
          }

          @page {
            size: 1080px 1920px;
            margin: 0;
          }
        }
      `}</style>
    </article>
  );
  */
}

